/*
	Skills:

	*Skillpoints -> handle the amount of skill points to distribute
	
	*Stealth -> Gives more damage over enemies while using a pistol
	*Support -> Gives more damage over enemies while using a SMG
	*Recon -> Gives more damage over enemies while using a sniper rifle
	*Assault -> Gives more damage over enemies while using an assault rifle
	*Guerrilla -> Gives more damage over enemies while using a shotgun
	*Endurance -> Take less damage when hitted by a player
	*Feeding -> Fell less hunger during the game time
	*Satiation -> Feel less thirst during the game time	
	*Engineering -> Faster repair duration
	*Handicraft -> Craft items faster
	*Absorption -> Less bleeding when take damage, faster cure and body fix
	*Reaction -> More radiation resistance
*/